language: php
php:
  - 5.6
  - 7
  - hhvm
install: composer install
script: ./vendor/bin/phpunit --coverage-clover clover.xml
after_success: sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" -a "$TRAVIS_PHP_VERSION" != "7" ]; then ./vendor/bin/coveralls -v; fi'
matrix:
  fast_finish: true
  allow_failures:
     - php: hhvm
